## Author

 - **Name:** Ruiqing Yu
 - **Email:** ruiqing6@illinois.edu

## Purpose

This is an useful tool to look for mean GPA value of every course from 2010 to 2021.
Students could look for mean GPA of every course in a specific major that in a specific year. The plot can show the trends of mean GPA value every year by dragging the slider.
They could also search for a specific course they are interested in, and see the trends of GPA change by dragging the slider of year.
They could also look up detailed information like the instructor in the table.

## Data

There are there variables you could modify in the APP page. The first slider controls the start year till 2021. The plot will show the mean GPA value of each course that from the start year till 2021. The second slider sets the lowest boundary of mean GPA. Courses that below this boundary will not show up in the plot. The last input is the name of a major or a specific course. The input should in form like this "stat385" or just name of major. Capital letter doesn't matter. The plot can also show the trend of mean GPA value by changing the start year. By changing the year, the information provided in the table will also change because each year the course lists are different. 

## References

data sourse: 
https://github.com/wadefagen/datasets.git